Vagrant.configure("2") do |config|

  # For more information on the modifyvm commands see http://www.virtualbox.org/manual/ch08.html
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.synced_folder "docker",                     "/data/docker"
  config.vm.synced_folder "scripts",                    "/data/scripts"
  config.vm.synced_folder "../",                        "/data/project"
  config.vm.synced_folder "C:/my/Dropbox/sinica-blog",  "/data/blog"

  config.vm.define "srv-blog-builder" do |srv|
    srv.vm.hostname = "srv-avvo-docker"
    srv.vm.network    "private_network", ip: "10.10.10.10"
    srv.vm.provider   "virtualbox" do |vb|
      vb.name   = "srv-blog-builder"
      vb.memory = 1024
    end
    srv.vm.provision "docker" do |d|
        d.images = ["ubuntu:14.04"]
    end
  end

end
